### ISSUE TITLE
Mismatch for # of observations in OC/Dashboard Stats vs CSV download

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#41] opened 2021-04-28 11:22 UTC
There appear to be a consistent mismatch between the # of observations shown in the CSV download against those shown on the statistics page in the Dashboard and observations in OC - the latter 2 both have the same numbers. It seems to consistently be out by 4; 4 less in the CSV download compared to the frontend. The fact that there are less in the download means it can't be linked to deleted observations.

**Comment by EmpressNaledi** [comment] 2021-05-20 14:09
I've just revisited this and noted the following:

1. Downloaded observations for Southall 
2. CSV shows last observation dated 12/05
3. Check OC using filter date range 11/05-20/05. This shows 3 obsv; 2 for the 12/05 and 1 for 19/05
4. Need to investigate why the obsv from the 19th doesn't show-up in the downloaded made on the 20/05
5. In addition, if you filter obsv in the dashboard to Southall but with no date range - the obsv for the 19/05 doesn't show. However, if you go to the observation overview page, without filtering a pilot case study, you can see the obsv made in Southall on the 19/05

**Comment by Javier-Gasca** [comment] 2021-05-26 07:05
![image](https://user-images.githubusercontent.com/82105889/119617009-9e98f080-be01-11eb-9932-a967f9ac54ef.png)
![image](https://user-images.githubusercontent.com/82105889/119616555-06027080-be01-11eb-84cc-13d5902c9c5e.png)
I have tried to reproduce the error and it shows the odor of 05/19.
Could you check it again?

**Comment by vvalvesga** [comment] 2021-05-26 07:24
we've test it and we haven't seen any error. We downloaded all Southall observations and check 19/05 observation appears and in the list too. And we did the other download filtering dates and the same result: that observation appears. 
Maybe, you saw the error with production environment not updated or i don't know what can be the cause.

In any case, we need more information in issues, we haven't created the app and sometimes we don't know which screen do you refers to. We need all the steps, how to go to the screen, screenshots, etc. 

Check it again and close this issue if you can't reproduce it @EmpressNaledi

**Comment by EmpressNaledi** [comment] 2021-05-26 09:56
Hi @vvalvesga I've checked and I'm getting the same as you rather than what was happening previously - so will close.

**Comment by EmpressNaledi** [comment] 2021-05-26 10:56
I've had to re-open @vvalvesga Because OC shows 263 Observations in the frontend but the download only has 259 records
![image](https://user-images.githubusercontent.com/12254027/119648311-36560900-be19-11eb-9e12-13dda0318c7a.png)
![image](https://user-images.githubusercontent.com/12254027/119648419-57b6f500-be19-11eb-808c-fcf3f742d759.png)

So even though the latest records are showing there are still some missing from the download

**Comment by EmpressNaledi** [comment] 2021-05-26 10:58
Can you check the DB for any records within Southall that have not been validated or that have been deleted in case this is the issue. Looking at the dashboard currently all those pending verification are either from Spain or have no address details. The are also all from user 77 and user 15

**Comment by EmpressNaledi** [comment] 2021-05-26 11:37
We've discovered that the download for today does not show the 4 observations made this morning 26/05/2021

**Comment by EmpressNaledi** [comment] 2021-05-26 13:35
We've done some further analysis and have come to the following conclusion - when you set a filter range in OC front end, the data it collects does not include everything date range. It seems to exclude the beginning and end of the date range by several hours. E.g filtering from 01/09/2020-30/09/2020 gives a total of 79 observations. However, the data download shows 85 from that date range. We researched and found the 6 missing observation from the OC frontend includes 2 from the 01/09/2020 (times = 12:11:06 & 13:03:10 - note the timestamp in the backend is offset by 1hr) also missing are 30/09/2020 (times = 13:44:32 ; 17:58:00; 18:08:50 & 21:52:20 - again offset by 1hr in the backend). It's worth noting that an observations for the 30/09/20 at 07:43:06 was included when filtering via OC. Equally, for the 01/09/2020 2 records were also included (times = 12:11:06 & 13:03:10). 
So we are not sure whether there is a time lag between observations submitted in OC frontend and the data that is received & updated in the backend dashboard. This is evident, for example today's download did not include the 4 observations that were captured in OC this morning.
Could it be the filter is using the meta data from the backend rather than the frontend timestamp?

**Comment by vvalvesga** [comment] 2021-05-26 14:18
![imagen](https://user-images.githubusercontent.com/48445869/119676257-02d9a580-be3e-11eb-864d-bfec8ff7474b.png)

**Comment by vvalvesga** [comment] 2021-05-26 14:25
I have isolated the problem, from zone 24 (Southall) there are 259, it is correct in backend and frontend.
The problem is that there are 2 zones in the database that point to Southall. Then you have to change the query or I'll see why this happens. Apparently one was erased and recreated. But it has been inconsistent and the front collects the observations of both areas. The backend does the query in a different way starting by taking the zone, since that is what the query consists of at that point.

**Comment by vvalvesga** [comment] 2021-05-26 14:26
About the other comments, I have not looked, you would have to open new issues and be better explained ,

**Comment by EmpressNaledi** [comment] 2021-05-26 14:48
![image](https://user-images.githubusercontent.com/12254027/119681102-ab393b00-be39-11eb-9ebc-f1b260571caa.png)
From the live server - it shows the 263 I discussed before

**Comment by EmpressNaledi** [comment] 2021-05-26 14:51
I've also tested when logged in and filtered based on Southall Case study and the same numbers show @vvalvesga 
![image](https://user-images.githubusercontent.com/12254027/119681713-36b2cc00-be3a-11eb-9690-0197eb0dd446.png)

**Comment by EmpressNaledi** [comment] 2021-05-26 14:53
> I have isolated the problem, from zone 24 (Southall) there are 259, it is correct in backend and frontend.
> The problem is that there are 2 zones in the database that point to Southall. Then you have to change the query or I'll see why this happens. Apparently one was erased and recreated. But it has been inconsistent and the front collects the observations of both areas. The backend does the query in a different way starting by taking the zone, since that is what the query consists of at that point.

Also note your screen-dump suggests that there are no other observations across most of the UK which is incorrect

**Comment by EmpressNaledi** [comment] 2021-05-26 14:56
Can you do a database query to see whether zone 24 (Southall) has 4 observation for today? Then run the same query on the deleted zone to see if they exist there?

**Comment by vvalvesga** [comment] 2021-05-26 14:57
I have isolated the problem and that is why I have concluded that there are 259 observations for that zone number 24.
I explain myself better. See the importance of explaining well
I've caused those results to come out. I have deleted / filtered the rest, to get out which ones are really from that zone.

**Comment by vvalvesga** [comment] 2021-05-26 15:16
I have to investigate further. But there are 2 zones in the database for Southall. And take 259 observations from zone 24 and 4 from zone 15

**Comment by EmpressNaledi** [comment] 2021-05-26 15:45
Please can you download the 4 observations from zone 15 and send it as a CSV via slack Pleeeeeeeeeeeeeeease! I need to send the data to the industry and municipality

**Comment by Malonsoroldan** [comment] 2021-06-07 15:03
Hard deletion of the old zone from the database will solve this issue for the moment.

**Comment by frasanz** [comment] 2021-06-07 15:20
When filtering, the frontend is sending bad query to the database:
`
select `odors`.`id`, `id_odor_type`, `id_user`, `odors`.`color`, `id_odor_intensity`, `id_odor_duration`, `id_odor_annoy`, `published_at`, `latitude`, `longitude` from `odors` inner join `locations` on `odors`.`id` = `locations`.`id_odor` inner join `odor_types` on `odors`.`id_odor_type` = `odor_types`.`id` where `id_odor_intensity` >= 1 and `id_odor_intensity` <= 7 and `id_odor_annoy` >= 1 and `id_odor_annoy` <= 9 and `published_at` >= '2021-06-01 17:09:00' and `published_at` <= '2021-06-02 17:09:00' and `status` = 'published' and `verified` = 1`

**Closed as completed** 2021-06-15 04:16 UTC
Labels: bug, Urgent
