### ISSUE TITLE
Zone Manager does not update on deletion and can be duplicated

### ISSUE THREAD

**Issue by JohanaSfC** [Ibercivis/odourcollect.eu#54] opened 2021-05-26 12:10 UTC
From the back office, I have designated my user as zone administrator of two communities. But then I decided to delete myself as zone administrator and they are still appearing in my study zones.

![image](https://user-images.githubusercontent.com/83076037/119656346-31c92a80-bdf0-11eb-9be3-c9f2855d77ba.png)

From the back office, if it appears updated and my user is not associated to any zone administrator.

![image](https://user-images.githubusercontent.com/83076037/119656685-92f0fe00-bdf0-11eb-9151-902bbbd954f2.png)

In addition, the zone administrator information is duplicated, i.e. I have been added as zone administrator four times to the FORUM and I am going to add myself a fifth time:

![image](https://user-images.githubusercontent.com/83076037/119657061-10b50980-bdf1-11eb-96ae-a73c8ba0a77a.png)

![image](https://user-images.githubusercontent.com/83076037/119657192-380bd680-bdf1-11eb-969b-033657cd8533.png)

In my study areas window, my user is included 5 times in the FORUM. 
![image](https://user-images.githubusercontent.com/83076037/119657311-5b368600-bdf1-11eb-92a7-51e9ff274091.png)

**Comment by AlexAmoSfC** [comment] 2021-05-27 08:47
since it's a failure in basic CRUD functionality and it's visibly impacting in users screen, I've tagged as urgent bug.
since it's only affecting zone admins , you may disagree with me about the urgency. Edit accordingly.

**Comment by AlexAmoSfC** [comment] 2021-07-01 13:21
Reopening this issue.
Maybe the code was fixed, but the data structure inside OC, which was affected by it, is still lingering around and causing problems.

In case that an issue is related to CRUD functionality, please bear in mind that we should always double check if the data structures have been affected, and try to correct them back to a sane state.

Also, I was wondering if you can modify the scheme to implement a composite unique index based on userid+zone in order to make this structure violation attempts clearly noticeable (or not, just a suggestion).

![oc zone admin dupe](https://user-images.githubusercontent.com/83209147/124130960-9c205b00-da7f-11eb-977f-2cdbe0e0f361.png)

Thanks.

**Comment by frasanz** [comment] 2021-07-19 16:59
What you're seeing is because it is not deleting the relation user-zone but adding a timestamp to the delete_at field:
mysql> select * from user_zones where id_user = 1317;
+-----+---------+---------+-------+---------------------+---------------------+---------------------+
| id  | id_zone | id_user | admin | deleted_at          | created_at          | updated_at          |
+-----+---------+---------+-------+---------------------+---------------------+---------------------+
| 180 |       1 |    1317 |  NULL | 2021-05-04 11:47:01 | 2021-05-04 11:41:03 | 2021-05-04 11:47:01 |
| 181 |       4 |    1317 |  NULL | 2021-05-04 11:47:05 | 2021-05-04 11:46:50 | 2021-05-04 11:47:05 |
| 182 |       1 |    1317 |  NULL | 2021-05-17 22:58:33 | 2021-05-04 12:18:31 | 2021-05-17 22:58:33 |
| 188 |       1 |    1317 |  NULL | 2021-05-26 11:51:03 | 2021-05-26 11:50:40 | 2021-05-26 11:51:03 |
| 189 |       1 |    1317 |     1 | 2021-05-26 12:03:48 | 2021-05-26 11:51:11 | 2021-05-26 12:03:48 |
| 190 |       1 |    1317 |     0 | NULL                | 2021-05-26 12:07:11 | 2021-05-26 12:08:33 |
| 192 |       4 |    1317 |  NULL | NULL                | 2021-06-08 16:57:51 | 2021-06-08 16:57:51 |
| 193 |      25 |    1317 |  NULL | NULL                | 2021-06-08 16:58:14 | 2021-06-08 16:58:14 |
| 194 |      27 |    1317 |  NULL | NULL                | 2021-06-08 16:58:24 | 2021-06-08 16:58:24 |
| 195 |      29 |    1317 |  NULL | NULL                | 2021-06-08 16:58:30 | 2021-06-08 16:58:30 |
+-----+---------+---------+-------+---------------------+---------------------+---------------------+
10 rows in set (0,00 sec)

So, my proposed solution is to show only in the "user list" users where the relation user-zone has deleted_at==NULL. Agreed @AlexAmoSfC? 

Other solution can be to really delete the relation user-list, but I'm not sure if something else can be broken

**Comment by AlexAmoSfC** [comment] 2021-07-19 17:21
@frasanz it seems that most regression-proof strategy is the first one. also, it seems logical that the presence of a field reporting "deletion without real deletion" like "deleted_at", implies that queries should have it into account of course!
so proceed with including the NULL check in the queries.
Thank you very much Fran

**Comment by frasanz** [comment] 2021-07-20 06:15
Done in fronttest (also for the xlsx file creation), please have a look before closing this

**Comment by AlexAmoSfC** [comment] 2021-08-20 13:42
Pending testing for confirmation @JohanaSfC @miguelherpas

**Comment by JohanaSfC** [comment] 2021-09-09 13:12
It works perfectly :) Thanks!

**Closed as completed** 2021-09-09 13:12 UTC
Labels: bug, Urgent
