### ISSUE TITLE
Filtering interface on small screens

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#19] opened 2021-03-29 14:40 UTC
I would suggest removing or providing an alternative interface design for small screens as the current layout doesn't work on a phone

**Comment by frasanz** [comment] 2021-04-23 12:35
Also (at least in iphone 12) you need to scroll to see all the list of categories

**Comment by RosaArias** [comment] 2021-04-23 13:09
I have the issue with iphone 12 Pro and both in iPhone 12 Pro and in my old iPhone 7 in cannot see the complete list of odour subtypes for the category of "industrial odours" - for the rest of types of odours is fine since the list of subtypes are shorter. 
Also, the button of "next" can only be seen partially, or you need to drag down.
Also, the filters are not displayed well and are not usable (since I cannot see the whole calendar, for example).

**Comment by AlexAmoSfC** [comment] 2021-06-28 15:03
Closed (duplicate of #44)

**Closed as completed** 2021-08-20 13:29 UTC
Labels: duplicate
